apiVersion: batch/v1
kind: Job
metadata:
  name: jianyu-nerf-brdf-lego # Replace with something like "${USER_NAME}-{EXP_NAME}"
  namespace: ucsd-haosulab
spec:
  ttlSecondsAfterFinished: 86400  # Wait one day to delete completed jobs
  template:
    spec:
      containers:
        - name: gpu-container
          image: victortao/nerf:latest  # docker image
          # imagePullPolicy: Always
          command:
            - "/bin/bash"
            - "-c"
          args:
            - "apt install -y imagemagick && pip install open3d && cd /jianyu-fast-vol/nerf-ir/nerf-pytorch && export PYTHONPATH=. && python train_nerf_ir2.py --config config/messytable-brdf-remote.yml --sceneid lego2"
            # For multiple commands, concatenate them with &&
          resources:
            requests:
              cpu: "4"
              memory: "10Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "6"
              memory: "16Gi"
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: rayc-fast-vol
              mountPath: /rayc-fast
            - name: rayc-slow-vol
              mountPath: /rayc-slow
            - name: isabella-fast-vol
              mountPath: /isabella-fast
            - name: isabella-slow-vol
              mountPath: /isabella-slow
            - name: messytable-slow-vol
              mountPath: /messytable-slow-vol
            - name: dshm
              mountPath: /dev/shm
            - name: jianyu-fast-vol
              mountPath: /jianyu-fast-vol
            - name: edward-slow-vol
              mountPath: /edward-slow-vol
              
      volumes:
        - name: rayc-fast-vol
          persistentVolumeClaim:
            claimName: rayc-fast-vol
        - name: rayc-slow-vol
          persistentVolumeClaim:
            claimName: rayc-slow-vol
        - name: isabella-fast-vol
          persistentVolumeClaim:
            claimName: isabella-fast-vol
        - name: isabella-slow-vol
          persistentVolumeClaim:
            claimName: isabella-slow-vol
        - name: messytable-slow-vol
          persistentVolumeClaim:
            claimName: messytable-slow-vol
        - name: jianyu-fast-vol
          persistentVolumeClaim:
            claimName: jianyu-fast-vol
        - name: edward-slow-vol
          persistentVolumeClaim:
            claimName: edward-slow-vol
        - name: dshm
          emptyDir:
            medium: Memory
            
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: nautilus.io/group
                    operator: In
                    values:
                    - haosu
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                    - NVIDIA-GeForce-RTX-2080-Ti
                      
  backoffLimit: 0  # The number of attempts to restart after crash
